### ISSUE TITLE
field order

### ISSUE THREAD

**Issue by fritsander** [UdenVH/KNMIr#1]
Hi,

I'm using your retrieveDataRange.R function to download historic weather data from the KNMI. What I noticed however is that the colnames order in your .R function is different from the order I get when using the KNMI website to download the same data. When I go to http://projects.knmi.nl/klimatologie/daggegevens/selectie.cgi and download everything the EV24 field is header of the last column where in your function it is somewhere in the middle. How is this possible? 

How can I determine the correct colnames order in which the data is downloaded using KNMI's script page? How can I determine what selection criteria I can send and how to do this?

Thanks a lot for your help.

Kind regards,

Fritsander

**Comment by UdenVH** [comment]
Hi Fritsander,

i stopped working on this branch of KNMIr. You can find an improved version here: https://github.com/bvhest/KNMIr

It also contains a vignette on how to use the package.

You can get the 'raw' column names from the KNMI API, or more readable column names with the function rename_columns_KNMI_data(). I realy dislike the primitive column names provided by this API.

success!

**Comment by fritsander** [comment]
Heel veel dank voor je snelle reactie.

Fritsander

**Comment by fritsander** [comment]
Thanks a lot for your quick response.

Fritsander

**Comment by fritsander** [comment]
How do I retrieve the 'raw' column names from the KNMI API? I don't know how that works.

Thanks.

Fritsander

**Comment by UdenVH** [comment]
check the vignette, it explans how to easily get the data.

The original knmi column names can be retrieved with:
```
knmi.raw <- get_climate_data_api(stationID = 260, # De Bilt (centraal)
                                 from = "20040101",
                                 to = "20151231")
```
